server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aitestpro?characterEncoding=UTF-8&useUnicode=true&nullCatalogMeansCurrent=true
    password: jdbairoot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  configuration:
    use-actual-param-name: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.aitestpro.entity