#server:
#  port: 8080

spring:
  application:
    name: aipro-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${aipro.db.host}:3306/aitestpro?characterEncoding=UTF-8&useUnicode=true&nullCatalogMeansCurrent=true
    password: ${aipro.db.pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  configuration:
    use-actual-param-name: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.aitestpro.entity